// <auto-generated />
namespace WMgr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RevertedChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RevertedChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201612282328468_RevertedChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
